### model
# FORCE_TORCHRUN=1 llamafactory-cli train examples/train_full/qwen2_5vl_full_sft_merge7_small_lr.yaml
model_name_or_path: /share/algorithm-brain/model/Qwen/Qwen2.5-VL-7B-Instruct
#adapter_name_or_path: saves/qwen2_5vl-7b/full/sft/majiang_turn_1016_merge6/checkpoint-500
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z1_config.json

### dataset
dataset: majiang_turn_train_multi ,toukan_train, majiang_train_fetch, majiang_train_annotated, qa_english, sim_vg, real_vg # video: mllm_video_demo
eval_dataset: majiang_turn_test_multi, toukan_test, majiang_test_fetch, majiang_test_annotated, majiang_turn_test_multi_origin, toukan_test_origin, majiang_test_fetch_origin, majiang_test_annotated_origin
eval_on_each_dataset: true
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /share_data/yanruilin/qwen2_5vl_full_sft_merge7_small_lr
logging_steps: 8
save_steps: 1500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-6 # 1.0e-6
num_train_epochs: 30
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 25
predict_with_generate: true
prediction_loss_only: false
do_predict: true