### model
# FORCE_TORCHRUN=1 llamafactory-cli train examples/train_full/qwen2_5vl_full_sft_new.yaml
model_name_or_path: /mnt/data/personal/ceyao/models/Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: majiang_turn_train_new # mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
eval_dataset: majiang_turn_test_new
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/full/sft/majiang_turn_0928
logging_steps: 8
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4 # 1.0e-6
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
predict_with_generate: true
prediction_loss_only: false
#do_predict: true