### model
# llamafactory-cli train examples/train_lora/qwen2_5vl_lora_sft_toukan.yaml
model_name_or_path: /mnt/data/personal/ceyao/models/Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: toukan_train # mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
eval_dataset: toukan_test
#eval_on_each_dataset: true
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/lora/sft/majiang_turn_1015_toukan_one
logging_steps: 2
save_steps: 250
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4 # 1.0e-6
num_train_epochs: 100
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 5
predict_with_generate: true
prediction_loss_only: false
do_predict: true
# 生成/解码建议（分类任务）
max_new_tokens: 8
do_sample: false
temperature: 0.0
top_p: 1.0
num_beams: 1
repetition_penalty: 1.0
